repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        exclude: go\.sum$
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.12.2
    hooks:
      - id: golangci-lint-config-verify
      - id: golangci-lint-full
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        pass_filenames: false
        types_or: [go, go-mod, go-sum]
        language: golang
        stages: [pre-commit, pre-push]
      - id: go-generate
        name: go generate
        entry: go generate ./...
        pass_filenames: false
        types_or: [go, go-mod, go-sum]
        language: golang
        stages: [pre-commit, pre-push]
      - id: go-short-tests
        name: go short tests
        entry: env gotestsum -- -cover -short ./...
        pass_filenames: false
        types_or: [go, go-mod, go-sum]
        language: golang
        stages: [pre-push]

default_install_hook_types: [pre-commit, pre-push]
